### ISSUE TITLE
Wrong app version in test

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar-webapp#67]
The deployed version in test is show current version `dev` instead of the current build.

**Comment by RMCampos** [comment]
@DerekRoberts I think we need a new way of updating the app version. Just raised a question on Discord.

**Comment by DerekRoberts** [comment]
App versioning is handled by GitHub packages.  Do you have an additional variable assigned that could be causing confusion?

https://github.com/bcgov/nr-spar-webapp/pkgs/container/nr-spar-webapp%2Ffrontend

**Comment by RMCampos** [comment]
@DerekRoberts I see. But can we retrieve this value from github actions? I want to be able to see the current running version from the webapp, like, from a env var.

**Comment by DerekRoberts** [comment]
@RMCampos No, but you can see from the package list or track PRs.  Want to brainstorm how to do this better on Monday?

**Comment by DerekRoberts** [comment]
@RMCampos This issue is blocked/hold until you're back from vacation.  Have a great time!  :)

**Comment by RMCampos** [comment]
Hey @DerekRoberts I'm back! Thanks.

**Comment by RMCampos** [comment]
Hi @DerekRoberts I think we have two cases here. One is the image version/tag and other the code versioning release tag. I know you've been busy with lots of stuff, but for now I'll re-enable the auto-release tag feature and then we can discuss better another time. Also @annibalsilva has some thoughts on this.

**Comment by DerekRoberts** [comment]
> Hi @DerekRoberts I think we have two cases here. One is the image version/tag and other the code versioning release tag. I know you've been busy with lots of stuff, but for now I'll re-enable the auto-release tag feature and then we can discuss better another time. Also @annibalsilva has some thoughts on this.

Sounds good!  Let's get this figured out.  :)

**Comment by DerekRoberts** [comment]
Repo and all workflows replaced.  See https://github.com/bcgov/nr-spar.
